# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
- task: AndroidSigning@3
  inputs:
    apkFiles: '**/*.apk'
    apksignerKeystoreFile: 'C:\Users\HP\Documents\KeyStore.jks'
    apksignerKeystorePassword: 'expo3030'
    apksignerKeystoreAlias: 'MyAndroidKey'
    apksignerKeyPassword: 'expo3030'
    apksignerFile: 'C:\Users\HP\Documents'
    zipalignFile: 'C:\Users\HP\Documents'
    tasks: 'assembleDebug'
